# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

version: "2"
# Options for analysis running.
run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.24"

linters:
  enable:
    - errcheck
    - goimports
    - golint
    - govet
    - staticcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0