package gateways

// SetComplexGateway ...
func SetComplexGateway(p DelegateParameter) {}

// SetEventBasedGateway ...
func SetEventBasedGateway(p DelegateParameter) {}

// SetExclusiveGateway ...
func SetExclusiveGateway(p DelegateParameter) {}

// SetInclusiveGateway ...
func SetInclusiveGateway(p DelegateParameter) {}

// SetParallelGateway ...
func SetParallelGateway(p DelegateParameter) {}
