package definitions

type STR_PTR *string

type CANCEL_EVENT_DEF_SLC []CancelEventDefinition
type COMPENSATE_EVENT_DEF_SLC []CompensateEventDefinition
type CONDITIONAL_EVENT_DEF_SLC []ConditionalEventDefinition
type ERROR_EVENT_DEF_SLC []ErrorEventDefinition
type ESCALATION_EVENT_DEF_SLC []EscalationEventDefinition
type LINK_EVENT_DEF_SLC []LinkEventDefinition
type MESSAGE_EVENT_DEF_SLC []MessageEventDefinition
type SIGNAL_EVENT_DEF_SLC []SignalEventDefinition
type TERMINATE_EVENT_DEF_SLC []TerminateEventDefinition
type TIMER_EVENT_DEF_SLC []TimerEventDefinition

type TCANCEL_EVENT_DEF_SLC []CancelEventDefinition
type TCOMPENSATE_EVENT_DEF_SLC []TCompensateEventDefinition
type TCONDITIONAL_EVENT_DEF_SLC []TConditionalEventDefinition
type TERROR_EVENT_DEF_SLC []ErrorEventDefinition
type TESCALATION_EVENT_DEF_SLC []EscalationEventDefinition
type TLINK_EVENT_DEF_SLC []LinkEventDefinition
type TMESSAGE_EVENT_DEF_SLC []MessageEventDefinition
type TSIGNAL_EVENT_DEF_SLC []SignalEventDefinition
type TTERMINATE_EVENT_DEF_SLC []TerminateEventDefinition
type TTIMER_EVENT_DEF_SLC []TTimerEventDefinition

type CANCEL_EVENT_DEF_PTR *CancelEventDefinition
type COMPENSATE_EVENT_DEF_PTR *CompensateEventDefinition
type CONDITIONAL_EVENT_DEF_PTR *ConditionalEventDefinition
type ERROR_EVENT_DEF_PTR *ErrorEventDefinition
type ESCALATION_EVENT_DEF_PTR *EscalationEventDefinition
type LINK_EVENT_DEF_PTR *LinkEventDefinition
type MESSAGE_EVENT_DEF_PTR *MessageEventDefinition
type SIGNAL_EVENT_DEF_PTR *SignalEventDefinition
type TERMINATE_EVENT_DEF_PTR *TerminateEventDefinition
type TIMER_EVENT_DEF_PTR *TimerEventDefinition
